package br.com.uniamerica.npju.Entity;

public enum Sentenca {
    PENDENTE, PROCEDENTE, PROCEDENTE_EM_PARTE, IMPROCEDENTE, OUTRO
} // DEVE CONTER CAMPO PARA DESCRICAO PARA = PROCEDENTE EM PARTE E OUTRO
